# protocol_tests cases that fail on Windows 10.0.26200, by cause. Windows CI
# skips each with its cause as the reason, so the run page lists every one.
{
  reasons = {
    socketpair = "builds on socketpair(), which Windows lacks";
    unixRule = "asserts the Unix resolution rule; Windows resolves local to plain";
    noDeferredAcquire = "plain has no deferred acquire: a subscribe or first call to an absent module waits out the connect timeout";
    qtHost = "builds a Qt RemoteTransportHost while Windows resolves the consumer to plain, a pairing Windows never runs; these cases fail the same way on macOS with the consumer forced to plain";
  };
  socketpair = [
    "PlainCancelPendingRaceTest.ARealConnectionDropsAReplyThatArrivesAfterCancel"
    "PlainCompletionSubOrderTest.AConcurrentFirstCallCannotOutrunTheSubscription"
    "PlainEventSubSharingTest.ACompletionThatOvertakesItsOwnResultIsStillDelivered"
    "PlainEventSubSharingTest.ANewConsumerAgainstAnOldHost"
    "PlainEventSubSharingTest.ASecondHandleDoesNotStealTheFirstsCompletionChannel"
    "PlainEventSubSharingTest.EveryHandleGetsEveryEmission"
    "PlainEventSubSharingTest.ReleasingOneHandleLeavesTheOtherSubscribed"
    "PlainEventSubSharingTest.SubscriptionsSurviveChurn"
    "PlainEventSubSharingTest.TeardownRemovesEverySubscription"
  ];
  unixRule = [
    "TransportFactoryTest.NeedsQtEventLoopFollowsTheResolutionRule"
  ];
  noDeferredAcquire = [
    "EventDeliveryNonBlocking.SubscribingToAnAbsentModuleReturnsImmediately"
    "ReadinessGatedExchangeTest.AFirstCallToAnAbsentTargetPaysTheAcquireBudgetOnlyOnce"
  ];
  qtHost = [
    "AllTransportsAndProviders/EventDeliveryMatrix.LpSubscribe_PublishThenSubscribe_Control/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.LpSubscribe_PublishThenSubscribe_Control/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.LpSubscribe_SubscribeThenPublish_Delivers/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.LpSubscribe_SubscribeThenPublish_Delivers/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.PublishThenSubscribe_Delivers/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.PublishThenSubscribe_Delivers/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReconnectReArmsAnArmedSubscription/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReconnectReArmsAnArmedSubscription/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReconnectWhileModuleIsDown_StillReArmsWhenItReturns/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReconnectWhileModuleIsDown_StillReArmsWhenItReturns/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReservedEvent_NamedSubscriptionIsRefused/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReservedEvent_NamedSubscriptionIsRefused/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReservedEvent_WildcardDoesNotCarryIt/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.ReservedEvent_WildcardDoesNotCarryIt/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.SubscribeRightAfterACall_DeliversImmediately/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.SubscribeRightAfterACall_DeliversImmediately/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.SubscribeThenPublish_Delivers/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.SubscribeThenPublish_Delivers/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.SubscriptionSurvivesUnloadAndReload/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.SubscriptionSurvivesUnloadAndReload/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.WhenObjectAvailable_ModuleAlreadyUp_FiresTrue/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.WhenObjectAvailable_ModuleAlreadyUp_FiresTrue/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.WhenObjectAvailable_ModuleAppearsLater_FiresExactlyOnce/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.WhenObjectAvailable_ModuleAppearsLater_FiresExactlyOnce/qt_remote_UniversalProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.WhenObjectAvailable_NotReArmedOnReconnect/qt_remote_QtProvider"
    "AllTransportsAndProviders/EventDeliveryMatrix.WhenObjectAvailable_NotReArmedOnReconnect/qt_remote_UniversalProvider"
    "DeferredSubscriptionTest.LpSubscribe_AfterPublish_Control"
    "DeferredSubscriptionTest.LpSubscribe_BeforePublish_Delivers"
    "DeferredSubscriptionTest.ManySubscriptionsBeforeArm_DoNotFreeAReplicaQtRoStillHolds"
    "DeferredSubscriptionTest.OnEventWhenAvailable_PublishBeforeSubscribe_Control"
    "DeferredSubscriptionTest.OnEventWhenAvailable_SubscribeBeforePublish_Delivers"
    "DeferredSubscriptionTest.OnEventWhenAvailable_Wildcard_PublishBeforeSubscribe_Control"
    "DeferredSubscriptionTest.OnEventWhenAvailable_Wildcard_SubscribeBeforePublish_Delivers"
    "DeferredSubscriptionTest.OneSubscriptionBeforeArm_Control"
    "FastProviderRestartTest.ALateSubscriberJoinsTheCurrentGeneration"
    "FastProviderRestartTest.ASourceReplacedOnALiveConnectionIsARestart"
    "FastProviderRestartTest.BackToBackHostSwapsAreEachARestart"
    "FastProviderRestartTest.ChurnOnAHealthyModuleIsNotARestart"
    "FastProviderRestartTest.LpClientSeesTheFastRestart"
    "FastProviderRestartTest.LpSubscribeOnAnArmedClientKeepsTheGeneration"
    "FastProviderRestartTest.ManualHoldsAcrossAFastRestart"
    "FastProviderRestartTest.RearmOntoAReestablishedTargetStillReportsArmed"
    "HandshakeNegativeCacheTest.AModuleThatWasMerelyLateIsProbedAgainRatherThanWrittenOff"
    "HandshakeNegativeCacheTest.AModuleWithNoHandshakeSurfaceIsStillRememberedOnceProven"
    "HandshakeTransportTest.ALegacyModuleFallsBackAndIsNotReProbed"
    "HandshakeTransportTest.AnUnseededAnchorRefusesEvenThoughTheSurfaceIsReachable"
    "HandshakeTransportTest.TokenReachesAModuleWhoseBusinessObjectIsNotPublishedYet"
    "HostServicesGrantTest.GrantedDeliveryReachesAModuleThatIsNotCapabilityModule"
    "QtRemoteCallErrorTest.AsyncSuccessCarriesAnEmptyError"
    "QtRemoteCallErrorTest.AsyncTimeoutCarriesTheCanonicalError"
    "ReadinessGatedExchangeTest.ACallToATargetThatIsAlreadyUpIsNotDelayedByTheGate"
    "ReadinessGatedExchangeTest.AnAsyncBurstToALateTargetMintsOnceAndCompletesWhenItAppears"
    "ReadinessGatedExchangeTest.AnAsyncCallToAWarmTargetIsNotDelayedByTheGate"
    "ReadinessGatedExchangeTest.TheExchangeIsNotAttemptedUntilTheTargetHasPublished"
    "RemoteEventTest.ConsumerReusesCachedHandleAcrossSyncAndAsyncCalls"
    "SubscriptionContinuityTest.LpClientStatusCb_DeliversLostThenArmed"
    "SubscriptionContinuityTest.LpSubscribe_GenerationAdvancesAcrossRestart"
    "SubscriptionContinuityTest.NoStatusCb_IsStillPlainSubscribe"
    "SubscriptionContinuityTest.ProviderRestart_ReportsLostThenArmedWithNewGeneration"
    "SubscriptionContinuityTest.ProviderStaysUp_NoLostAndGenerationStaysOne"
    "SubscriptionRestartPolicyTest.AClientWithNoOptionsStaysAutomatic"
    "SubscriptionRestartPolicyTest.AHeldSubscriptionCanBeCancelled"
    "SubscriptionRestartPolicyTest.ALossWithNothingArmedReportsNothing"
    "SubscriptionRestartPolicyTest.AutomaticIsUnchanged"
    "SubscriptionRestartPolicyTest.InstallingAWatcherReplaysTheCurrentState"
    "SubscriptionRestartPolicyTest.LpClientOptionsCarryTheManualPolicy"
    "SubscriptionRestartPolicyTest.ManualHoldsInsteadOfReArming"
    "SubscriptionRestartPolicyTest.ManualStillArmsDeferred"
    "SubscriptionRestartPolicyTest.PolicySetBeforeAnySubscriptionStillApplies"
    "SubscriptionRestartPolicyTest.RearmRefusesWhatIsNotHeld"
    "SubscriptionRestartPolicyTest.RearmRevivesAHeldSubscription"
    "SubscriptionRestartPolicyTest.SubscriptionsToOneModuleTransitionTogether"
    "SubscriptionRestartPolicyTest.ThePolicyAppliesToEverySubscriptionOnTheModule"
    "TokenCacheTest.AsyncCallsToSameTargetHandshakeOnceAcrossBursts"
    "TokenCacheTest.SyncCallsToSameTargetHandshakeOnce"
    "TokenCacheTest.UnTokenedCallBoundsTheHandshakeByTheCallersBudget"
    "TokenReexchangeTest.AsyncRejectionReexchangesAndRetriesOnce"
    "TokenReexchangeTest.SyncEmptyResultDoesNotReexchange"
    "TokenReexchangeTest.SyncPersistentRejectionRetriesOnceThenGivesUp"
    "TokenReexchangeTest.SyncRejectionReexchangesAndRetriesOnce"
  ];
}
